### ISSUE TITLE
Remove duplicated imports

### ISSUE THREAD

**Issue by Sud0nim** [Bennyelg/csvql#1]
Hi Benny,

Cool project 😃 I noticed that some imports were duplicated and can be removed in the main src file (csvql.nim):

    import db_sqlite
    import strutils
    import sequtils
    import streams
    import tables
    import typetraits
    import parsecsv
    import docopt
    import strutils      # duplicate
    import tables       # duplicate
    import os
    import parseopt2
    import nre
    import strscans

Nothing major, just something that caught my eye when I was taking a look.

**Comment by Bennyelg** [comment]
Agree, I was asked for some tool in-order to avoid this kind of issues and remove duplication and unused imports but no library out there.
maybe I should write one down :D

Thanks.

**Comment by Bennyelg** [comment]
Fixed

**Comment by Sud0nim** [comment]
It would be good if the compiler gave this as a warning, but it always seems that there is some good reason that it hasn't been added :) I'm not sure what it is though
